// Client names shown in the home-page marquee and on the Our Clients page.

export const clients = [
  "AECB",
  "Abu Dhabi International Airport",
  "ADNOC",
  "Agnice",
  "Ahmed Saddiqi",
  "Ahmed Tea",
  "Air Arabia",
  "Al Ain Holdings",
  "Al Fahim",
  "Al Futtaim Group",
  "Al Jazeera Investment",
  "Al Khaleej Steel",
  "Al Madallah",
  "Al Masraf",
  "Al Reyami Advocates",
  "American Gulf School – Sharjah",
  "ARADA",
  "Arab Link",
  "ARENCO",
  "Asma Hotel",
  "Bank Muscat",
  "Barraquer Eye Hospital",
  "BITS Pilani Dubai",
  "Canadian Hospital",
  "Carlton Hotel",
  "Carrefour",
  "Citi Bank",
  "Commercial Bank of Dubai",
  "CTS Roadside Assistance",
  "CTS-KHADA",
  "Damac Properties",
  "Dana Beach Resort",
  "Dana Bay",
  "Data Direct",
  "Department of Health Abu Dhabi",
  "Desert Gate",
  "DEWA",
  "DIFC",
  "DP World",
  "Du Telecom / DU",
  "Dubai Airports",
  "Dubai Frame",
  "Dubai Investment Park",
  "Dubai Investment Real Estate",
  "Dubai Land Department",
  "Dubai Mall",
  "Dubai Metro",
  "Dubai Tourism",
  "Earnest Insurance",
  "Easy Lease",
  "Emaar",
  "Emirates Driving Company",
  "Emirates NBD Bank",
  "Emitech",
  "Enova International",
  "ENOC",
  "Etihad Airways",
  "Etisalat Afghanistan",
  "Etisalat / e&",
  "Excellence Driving Institute",
  "FAB Bank",
  "Finance House",
  "Flydubai",
  "Fujairah Customs",
  "Fujairah National Group",
  "G42",
  "Galadari / Galadari Driving",
  "Geco Mechanical & Electrical",
  "GEMS Education",
  "GEMS Metropole",
  "GEMS Millennium School",
  "GEMS World Academy",
  "Gewan Hotels & Resorts",
  "GFS Ship Management",
  "Green Motor",
  "Hily Holding",
  "Hilton / Hilton Business Bay / Hilton Hotel",
  "IKEA",
  "Injazat",
  "Infosat",
  "Infosys",
  "Insurance House",
  "International Community Schools",
  "International Gas Services (Sergas)",
  "JAFZA",
  "Kalba Health Center (EHS)",
  "Lexus",
  "Liberty Computer",
  "Liwa Insurance",
  "Majid Al Futtaim",
  "Marks & Spencer",
  "Mashreq Bank",
  "Masdar City",
  "Medcare",
  "Meraas",
  "Mercure Hotel",
  "Ministry of Community Development",
  "Ministry of Human Resources and Emiratisation / Ministry of Labor",
  "Mubadala",
  "Nakheel",
  "National Finance",
  "Next Care (Enaya)",
  "Noor Takaful",
  "Occidental Hotels and Resorts",
  "Omantel",
  "Omnisat",
  "Omtrack",
  "Pan Home",
  "Prime Medical Center",
  "Progress Group",
  "Reem Hospital",
  "Reem Neuroscience Centre",
  "RTA Dubai",
  "SAIF Zone",
  "Sautt Technology",
  "Scientechnic (Fujairah Port)",
  "Scitra",
  "Sharjah Islamic Bank",
  "Sharjah Women's Club",
  "Siemcom Hassantuk",
  "Skoda",
  "SPC Free Zone",
  "Swissôtel Al Ghurair",
  "TAQA Energy",
  "TCT",
  "TDRA",
  "Tecom Group",
  "Telematics",
  "Teleperformance",
  "The Executive Office of Her Highness Sheikha Jawaher, Sharjah",
  "The Westminster School, Dubai",
  "Tokio Marine Insurance",
  "Toyota",
  "Unitech",
  "Vision Tech",
  "VocalCom",
  "WASL Properties",
  "Xiaomi",
  "Zajel",
  "Zulekha Hospital"
];